version: '3.8'

services:

  pgadmin:
    restart: always
    container_name: main-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 90:80

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: main-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
      - ./server:/usr/share/nginx/server
  
  cors-anywhere:
    restart: always
    container_name: main-cors-anywhere
    image: testcab/cors-anywhere 
    ports:
      - 81:8080

  postgres:
    restart: always
    image: postgres:11.11-alpine
    container_name: main-postgres
    volumes:
        - postgres:/var/lib/postgresql/data
    environment: 
        POSTGRES_DB: main
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

volumes:
  .:
  pgadmin:
  postgres:
